select * from behaviour limit 20

-- what is the total revenue generated by male vs female customers 
select gender, sum(purchase_amount) as total_revenue
from behaviour 
group by gender


# Which customers used a discount but still spent more than the average purchase amount? 

select customer_id
from behaviour
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from behaviour)


# Which are the top 5 products with the highest average review rating?

select item_purchased, avg(review_rating) as avg_rating
from behaviour
group by item_purchased
order by avg_rating desc
limit 5


# Compare the average Purchase Amounts between Standard and Express Shipping.

select shipping_type, avg(purchase_amount)
from behaviour
where shipping_type in ('Standard','Express')
group by shipping_type


# Do subscribed customers spend more? Compare average spend and total revenue 

select subscription_status, count(customer_id) as total_customers, avg(purchase_amount) as avg_spend , sum(purchase_amount) as total_revenue
from behaviour
group by subscription_status


# Which 5 products have the highest percentage of purchases with discounts applied?

SELECT item_purchased,
       ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS discount_rate
FROM behaviour
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


# Segment customers into New, Returning, and Loyal based on their total 
-- number of previous purchases, and show the count of each segment.

select
case when previous_purchases =1 then 'New'
when previous_purchases between 2 and 10 then 'Returning' else 'Loyal' end as Segment,
count(customer_id) as total_customers
from behaviour
group by segment 


# What are the top 3 most purchased products within each category? 

with tbl as (select category, item_purchased, count(customer_id) as total_customers,
rank() over(partition by category order by count(customer_id) desc) as rnk
from behaviour
group by category,item_purchased)
select category, item_purchased, total_customers
from tbl 
where rnk <4


-- Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?

select subscription_status, count(customer_id)
from behaviour
where previous_purchases > 5
group by subscription_status


-- What is the revenue contribution of each age group? 

select age_groups, sum(purchase_amount)
from behaviour
group by age_groups




